# Setup
title:               CDL Handbook
tagline:             'SUNY Geneseo Center for Digital Learning'
description:         'Handbook for CDL student affiliates'
url:                 https://cdl-geneseo.github.io/handbook
baseurl:             https://cdl-geneseo.github.io/handbook/
paginate:            5
permalink:           pretty 

# About/contact
author:
  name:              Center for Digital Learning
  url:               https://www.geneseo.edu/cdl/handbook
  email:             cdl@geneseo.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
